services:
  postgres:
    image: postgres:18.4
    restart: always
    ports:
      - "5582:5432"
    environment:
      POSTGRES_USER: dsk
      POSTGRES_PASSWORD: dsk
      POSTGRES_DB: dsk
    volumes:
      - dsk-dev_db:/var/lib/postgresql

volumes:
  dsk-dev_db: