spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml

  config:
    import: optional:file:./.env[.properties]

  application:
    name: dsk
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
