spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml

  config:
    import: optional:file:./.env[.properties]

  application:
    name: dsk

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          authsch:
            client-id: "59664918612575202731"
            client-secret: "szVYihbiGD5EeEFSroZhOJUJ7IbhGjUAAqwDcaoILF8dtlryOYGJUjLCwsfhHRGYCHvbnaXbhMxW8CuH"
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/authsch"
          google:
            client-id: "asdf"
            client-secret: "asdf"
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

        provider:
          authsch:
            authorization-uri: "https://auth.sch.bme.hu/site/login"
            token-uri: "https://auth.sch.bme.hu/oauth2/token"
            user-name-attribute: internal_id
            user-info-authentication-method: header
            user-info-uri: "https://auth.sch.bme.hu/oidc/userinfo"
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://accounts.google.com/o/oauth2/token"

logging:
  level:
    root: DEBUG
    hu.bme.dsk: DEBUG


hu:
  bme:
    dsk:
      startup:
        secret-key: secret-keyffffffffffffffffffffffffffffffffffff
        session-validity-seconds: 36000
        sysadmins: "asdf"
